// songs.js

const songs = [
    // 80s / 90s
    { title: 'Billie Jean', artist: 'Michael Jackson', file: 'michael_jackson_billie_jean.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Bohemian Rhapsody', artist: 'Queen', file: 'queen_bohemian_rhapsody.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'We Will Rock You', artist: 'Queen', file: 'queen_we_will_rock_you.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Don’t Stop Me Now', artist: 'Queen', file: 'queen_dont_stop_me_now.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Livin’ on a Prayer', artist: 'Bon Jovi', file: 'bon_jovi_livin_on_a_prayer.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Sweet Child O’ Mine', artist: 'Guns N’ Roses', file: 'guns_roses_sweet_child_o_mine.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Smells Like Teen Spirit', artist: 'Nirvana', file: 'nirvana_smells_like_teen_spirit.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'I Don’t Want to Miss a Thing', artist: 'Aerosmith', file: 'aerosmith_i_dont_want_to_miss_a_thing.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Like a Prayer', artist: 'Madonna', file: 'madonna_like_a_prayer.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Every Breath You Take', artist: 'The Police', file: 'the_police_every_breath_you_take.mp3', fragmentDurations: [3, 5, 7, 10]},
    
    { title: 'Love Me Again', artist: 'John Newman', file: 'john_newman_love_me_again.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Obsesionario En La Mayor', artist: 'Tan Bionica', file: 'tan_bionica_obsesionario_en_la_mayor.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Ciudad Mágica', artist: 'Tan Bionica', file: 'tan_bionica_ciudad_magica.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Bad Habits', artist: 'Ed Sheeran', file: 'ed_sheeran_bad_habits.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Waiting For Love', artist: 'Avicii', file: 'avicii_waiting_for_love.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Sugar', artist: 'Maroon 5', file: 'maroon_5_sugar.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Feel Good', artist: 'Gorillaz', file: 'gorillaz_feel_good.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Lose Control', artist: 'Teddy Swims', file: 'teddy_swims_lose_control.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'All Star', artist: 'Smash Mouth', file: 'smash_mouth_all_star.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Boulevard Of Broken Dreams', artist: 'Green Day', file: 'green_day_boulevard_of_broken_dreams.mp3', fragmentDurations: [3, 5, 7, 10]},
    
    { title: 'Bad', artist: 'David Guetta', file: 'david_guetta_bad.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Sweater Weather', artist: 'The Neighbourhood', file: 'the_neighbourhood_sweater_weather.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'The Line', artist: 'Twenty One Pilots', file: 'twenty_one_pilots_the_line.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Californication', artist: 'Red Hot Chili Peppers', file: 'red_hot_chili_peppers_californication.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Sweet Dreams', artist: 'Eurythmics', file: 'eurythmics_sweet_dreams.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'I Was Made For Lovin’ You', artist: 'Kiss', file: 'kiss_i_was_made_for_lovin_you.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Smooth Criminal', artist: 'Michael Jackson', file: 'michael_jackson_smooth_criminal.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Sugar', artist: 'Robin Schulz', file: 'robin_schulz_sugar.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Mentía', artist: 'Miranda', file: 'miranda_mentía.mp3', fragmentDurations: [3, 5, 7, 10]},
    
    { title: 'Circles', artist: 'Post Malone', file: 'post_malone_circles.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Stressed Out', artist: 'Twenty One Pilots', file: 'twenty_one_pilots_stressed_out.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Blinding Lights', artist: 'The Weeknd', file: 'the_weeknd_blinding_lights.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Counting Stars', artist: 'OneRepublic', file: 'oneRepublic_counting_stars.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'STAY', artist: 'Kid LAROI', file: 'kid_laroi_stay.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'American Idiot', artist: 'Green Day', file: 'green_day_american_idiot.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'No Money', artist: 'Galantis', file: 'galantis_no_money.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Play Hard', artist: 'David Guetta', file: 'david_guetta_play_hard.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Rap God', artist: 'Eminem', file: 'eminem_rap_god.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Lose Yourself', artist: 'Eminem', file: 'eminem_lose_yourself.mp3', fragmentDurations: [3, 5, 7, 10]},
    
    { title: 'LA PLENA', artist: 'Beéle', file: 'beele_la_plena.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Bandolero', artist: 'Don Omar', file: 'don_omar_tego_calderon_bandolero.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Ella y Yo', artist: 'Aventura', file: 'aventura_ella_y_yo.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Torero', artist: 'Chayanne', file: 'chayanne_torero.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Ahora te puedes marchar', artist: 'Luis Miguel', file: 'luis_miguel_ahora_te_puedes_marchar.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'HOLA PERDIDA', artist: 'Luck Ra', file: 'luck_ra_hola_perdida.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'YA NO VUELVAS', artist: 'La Konga', file: 'luck_ra_ya_no_vuelvas.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'LA MOROCHA', artist: 'Luck Ra', file: 'luck_ra_la_morocha.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Nena', artist: 'Marama', file: 'marama_nena.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'WHERE SHE GOES', artist: 'Bad Bunny', file: 'bad_bunny_where_she_goes.mp3', fragmentDurations: [3, 5, 7, 10]},

    { title: 'Punto G', artist: 'Quevedo', file: 'quevedo_punto_G.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Radioactive', artist: 'Imagine Dragons', file: 'imagine_dragons_radioactive.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Bangarang', artist: 'SKRILLEX', file: 'skrillex_bangarang.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'In The End', artist: 'Linkin Park', file: 'linkin_park_in_the_end.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Bring Me To Life', artist: 'Evanescence', file: 'evanescence_bring_me_to_life.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Campanas en la noche', artist: 'Los Tipitos', file: 'los_tipitos_campanas_en_la_noche.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Brujeri­a', artist: 'Los Tipitos', file: 'los_tipitos_brujeria.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Blank Space', artist: 'Taylor Swift', file: 'taylor_swift_blank_space.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Look What You Made Me Do', artist: 'Taylor Swift', file: 'taylor_swift_look_what_you_made_me_do.mp3', fragmentDurations: [3, 5, 7, 10]},
    // { title: 'Shake It Off', artist: 'Taylor Swift', file: 'taylor_swift_shake_it_off.mp3', fragmentDurations: [3, 5, 7, 10]}, // ARCHIVO FALTANTE

    { title: 'CAN’T STOP THE FEELING', artist: 'Justin Timberlake', file: 'justin_timberlake_cant_stop_the_feeling.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Drag Me Down', artist: 'One Direction', file: 'one_direction_drag_me_down.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Moves Like Jagger', artist: 'Maroon 5', file: 'maroon_5_moves_like_jagger.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Watermelon Sugar', artist: 'Harry Styles', file: 'harry_styles_watermelon_sugar.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Safe And Sound', artist: 'Capital Cities', file: 'capital_cities_safe_and_sound.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Bye Bye Bye', artist: 'NSYNC', file: 'nsync_bye.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'I Want It That Way', artist: 'Backstreet Boys', file: 'backstreet_boys_i_want_it_that_way.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Never Say Never', artist: 'Justin Bieber', file: 'justin_bieber_never_say_never.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Sorry', artist: 'Justin Bieber', file: 'justin_bieber_sorry.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Baby One More Time', artist: 'Britney Spears', file: 'britney_spears_baby_one_more_time.mp3', fragmentDurations: [3, 5, 7, 10]},

    { title: 'Can’t Feel My Face', artist: 'The Weeknd', file: 'the_weeknd_can_t_feel_my_face.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Closer', artist: 'The Chainsmokers', file: 'the_chainsmokers_closer.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'good 4 u', artist: 'Olivia Rodrigo', file: 'olivia_rodrigo_good_4_u.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Shape of You', artist: 'Ed Sheeran', file: 'ed_sheeran_shape_of_you.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Rude', artist: 'MAGIC!', file: 'magic_rude.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Beautiful Things', artist: 'Benson Boone', file: 'benson_boone_beautiful_things.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'What Makes You Beautiful', artist: 'One Direction', file: 'one_direction_what_makes_you_beautiful.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Old Town Road', artist: 'Lil Nas', file: 'lil_nas_old_town_road.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'See You Again', artist: 'Wiz Khalifa', file: 'wiz_khalifa_see_you_again.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'God’s Plan', artist: 'Drake', file: 'drake_gods_plan.mp3', fragmentDurations: [3, 5, 7, 10]},

    { title: 'MONTERO', artist: 'Lil Nas', file: 'lil_nas_montero.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Balada Del Diablo y La Muerte', artist: 'La Renga', file: 'la_renga_balada_del_diablo_y_la_muerte.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Mil Horas', artist: 'Los abuelos de la nada', file: 'los_abuelos_de_la_nada_mil_horas.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Arde la ciudad', artist: 'Mancha de Rolando', file: 'mancha_de_rolando_arde_la_ciudad.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Por Mil Noches', artist: 'AIRBAG', file: 'airbag_por_mil_noches.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Amor Clasificado', artist: 'Rodrigo', file: 'rodrigo_amor_clasificado.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Curiosidad', artist: 'Rombai', file: 'rombai_curiosidad.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Hoy Volvi A Verte', artist: 'El Retutu', file: 'el_retutu_hoy_volvi_a_verte.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Soy Sabalero', artist: 'Los Palmeras', file: 'los_palmeras_soy_sabalero.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Pasos al costado', artist: 'Turf ', file: 'turf_pasos_al_costado.mp3', fragmentDurations: [3, 5, 7, 10]},

    { title: 'Zafar', artist: 'La Vela Puerca', file: 'la_vela_puerca_zafar.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Don', artist: 'Miranda', file: 'miranda_don.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Putita', artist: 'Babasonicos', file: 'babasonicos_putita.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Irresponsables', artist: 'Babasonicos', file: 'babasonicos_irresponsables.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Sharks', artist: 'Imagine Dragons', file: 'imagine_dragons_sharks.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Take Me To Church', artist: 'Hozier', file: 'hozier_take_me_to_church.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Dream On', artist: 'Aerosmith', file: 'aerosmith_dream_on.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Clint Eastwood', artist: 'Gorillaz', file: 'gorillaz_clint_eastwood.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Creep', artist: 'Radiohead', file: 'radiohead_creep.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Somewhere over the Rainbow', artist: 'Israel', file: 'israel_somewhere_over_the_rainbow.mp3', fragmentDurations: [3, 5, 7, 10]},

    { title: 'I Will Survive', artist: 'Gloria Gaynor', file: 'gloria_gaynor_i_will_survive.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'FEEL ME?', artist: 'Trueno', file: 'trueno_feel_me.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'September', artist: 'Earth, Wind & Fire', file: 'earth_wind_y_fire_september.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Humanos a Marte', artist: 'Chayanne', file: 'chayanne_humanos_a_marte.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'A Dios Le Pido', artist: 'Juanes', file: 'juanes_a_dios_le_pido.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Azul', artist: 'Cristian Castro', file: 'cristian_castro_azul.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Flaca', artist: 'Andrés Calamaro', file: 'andres_calamaro_flaca.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'De Musica Ligera', artist: 'Soda Stereo', file: 'soda_stereo_de_musica_ligera.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Crimen', artist: 'Gustavo Cerati', file: 'gustavo_cerati_crimen.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Nada Fue Un Error', artist: 'Coti ', file: 'coti_nada_fue_un_error.mp3', fragmentDurations: [3, 5, 7, 10]},

    { title: 'Color Esperanza', artist: 'Diego Torres', file: 'diego_torres_color_esperanza.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Noviembre Sin Ti', artist: 'Reik', file: 'reik_noviembre_sin_ti.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Angels', artist: 'Robbie Williams', file: 'robbie_williams_angels.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Wonderwall', artist: 'Oasis', file: 'oasis_wonderwall.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Tu Sin Mi', artist: 'Dread Mar I', file: 'dread_mar_i_tu_sin_mi.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Taboo', artist: 'Don Omar', file: 'don_omar_taboo.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Perdoname', artist: 'La Factoría', file: 'perdoname_la_factoria.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Otra Vez', artist: 'Zion & Lennox', file: 'zion_&_lennox_otra_vez.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'capaz', artist: 'Alleh', file: 'alleh_&_yorghaki_capaz.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Tu jardín con enanitos', artist: 'Roze', file: 'roze_tu_jardin_con_enanitos.mp3', fragmentDurations: [3, 5, 7, 10]},

    { title: 'Umbrella', artist: 'Rihanna ', file: 'rihanna_umbrella.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Pump It', artist: 'The Black Eyed Peas', file: 'the_black_eyed_peas_pump_it.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'goosebumps', artist: 'Travis Scott', file: 'travis_scott_goosebumps.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Smack That', artist: 'Akon ', file: 'akon_smack_that.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Gym Class Heroes', artist: 'Stereo Hearts', file: 'stereo_hearts_gym_class_heroes.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Right Now', artist: 'Akon', file: 'akon_right_now.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Diamonds', artist: 'Rihanna', file: 'rihanna_diamonds.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'The Lazy Song', artist: 'Bruno Mars', file: 'bruno_mars_the_lazy_song.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Starboy', artist: 'The Weeknd', file: 'the_weeknd_starboy.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Human', artist: 'Ragn Bone Man', file: 'ragn_bone_man_human.mp3', fragmentDurations: [3, 5, 7, 10]},

    { title: 'Ordinary', artist: 'Alex Warren', file: 'alex_warren_ordinary.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Thunder', artist: 'Imagine Dragons', file: 'imagine_dragons_thunder.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Hoy', artist: 'Valentino Merlo', file: 'valentino_merlo_hoy.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'DÁKITI', artist: 'BAD BUNNY', file: 'bad_bunny_dakiti.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Amor de Vago', artist: 'LA T Y LA M', file: 'la_t_y_la_m_amor_de_vago.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Ella Baila Sola', artist: 'Peso Pluma', file: 'peso_pluma_ella_baila_sola.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'GIVENCHY', artist: 'DUKI', file: 'duki_givenchy.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'She Don t Give a FO', artist: 'Duki', file: 'duki_she_dont_give_a_fo.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'AMORFODA', artist: 'BAD BUNNY', file: 'bad_bunny_amorfoda.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'dime si eres feliz', artist: 'la champions liga', file: 'la_champions_liga_dime_si_eres_feliz.mp3', fragmentDurations: [3, 5, 7, 10]},

    { title: 'Deja de llorar', artist: 'El Polaco', file: 'el_polaco_deja_de_llorar.mp3', fragmentDurations: [3, 5, 7, 10]},
    { title: 'Me Extrañarás', artist: 'De La Calle', file: 'de_la_calle_me_extranas.mp3', fragmentDurations: [3, 5, 7, 10]},
];

// Exporta el array para que pueda ser importado en otros archivos
module.exports = songs;